# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "debian"

  # Adding private network interface
  config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN2-6" 
  config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN4-6" 

  config.vm.hostname = File.basename(Dir.getwd)

  ### Shared repository
  config.vm.synced_folder ".", "/vagrant", owner: "root"
  config.vm.synced_folder "../shared", "/mnt/shared", create: true, owner: "root" 

  # virtualbox settings
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true  # performance
    vb.gui = true
    # Memory setting
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    vb.customize ["modifyvm", :id, "--vram", "16"]

    # Copy-paste, for virtualbox >= 6.1
    vb.customize 'post-boot', ['controlvm', :id, 'clipboard', 'mode', 'bidirectional']
  end

end

